version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - .:/app
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'twfy-votes'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    working_dir: /app
  web:
    image: mysociety/twfy-votes:${TAG:-latest}
    build: .
    command: /app/script/server --development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    tty: true
    environment:
      SECRET_KEY: 'secret'
      DEBUG: 1
      DATABASE_URL: 'postgres://postgres:password@db/twfy-votes'
      EMAIL_HOST: email.svc
      CACHE_FILE: 'data/cache'
      GOOGLE_ANALYTICS: ${GOOGLE_ANALYTICS:-}
      DJANGO_SUPERUSER_USERNAME: 'admin'
      DJANGO_SUPERUSER_PASSWORD: 'password'
      DJANGO_SUPERUSER_EMAIL: 'admin@localhost'
    working_dir: /app

volumes:
  pgdata:
  build:
  node_modules: