# Generated by Django 4.2.15 on 2024-08-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_alter_governmentparty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='division',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='division',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='governmentparty',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='governmentparty',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='governmentparty',
            name='start_date',
            field=models.DateField(),
        ),
    ]
