# Generated by Django 4.2.15 on 2024-08-30 11:26

from django.db import migrations, models
import django.db.models.deletion
import votes.consts


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_governmentparty_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('context_description', models.TextField()),
                ('policy_description', models.TextField()),
                ('notes', models.TextField(default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('candidate', 'Candidate'), ('draft', 'Draft'), ('rejected', 'Rejected'), ('retired', 'Retired')], max_length=255)),
                ('strength_meaning', models.CharField(choices=[('classic', 'Classic'), ('simplified', 'Simplified')], default=votes.consts.StrengthMeaning['SIMPLIFIED'], max_length=255)),
                ('highlightable', models.BooleanField(default=False)),
                ('chamber_id', models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('ni', 'Ni')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyGroup',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('slug', models.CharField(choices=[('health', 'Health'), ('misc', 'Misc'), ('social', 'Social'), ('reform', 'Reform'), ('foreignpolicy', 'Foreignpolicy'), ('environment', 'Environment'), ('education', 'Education'), ('taxation', 'Taxation'), ('business', 'Business'), ('transport', 'Transport'), ('housing', 'Housing'), ('home', 'Home'), ('justice', 'Justice'), ('welfare', 'Welfare')], max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='division',
            name='clock_time',
        ),
        migrations.RemoveField(
            model_name='division',
            name='division_id',
        ),
        migrations.RemoveField(
            model_name='division',
            name='manual_motion',
        ),
        migrations.RemoveField(
            model_name='division',
            name='motion',
        ),
        migrations.RemoveField(
            model_name='division',
            name='source_url',
        ),
        migrations.AddField(
            model_name='agreement',
            name='key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='absent_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='abstain_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='majority_vote',
            field=models.CharField(choices=[('aye', 'Aye'), ('no', 'No')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='no_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='yes_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreement',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PolicyDivisionLink',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('alignment', models.CharField(choices=[('agree', 'Agree'), ('against', 'Against'), ('neutral', 'Neutral')], max_length=255)),
                ('strength', models.CharField(choices=[('weak', 'Weak'), ('strong', 'Strong')], default=votes.consts.PolicyStrength['WEAK'], max_length=255)),
                ('notes', models.CharField(default='', max_length=255)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_links', to='votes.division')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_links', to='votes.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyAgreementLink',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('alignment', models.CharField(choices=[('agree', 'Agree'), ('against', 'Against'), ('neutral', 'Neutral')], max_length=255)),
                ('strength', models.CharField(choices=[('weak', 'Weak'), ('strong', 'Strong')], default=votes.consts.PolicyStrength['WEAK'], max_length=255)),
                ('notes', models.CharField(default='', max_length=255)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_links', to='votes.agreement')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_links', to='votes.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='groups',
            field=models.ManyToManyField(related_name='policies', to='votes.policygroup'),
        ),
    ]
