# Generated by Django 4.2.15 on 2024-12-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_agreement_negative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('date_created', models.DateTimeField(null=True)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('instructions', models.JSONField()),
                ('created_via', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
