# Generated by Django 4.2.15 on 2024-08-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0007_chamber_remove_division_chamber_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='chamber_slug',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('pbc', 'Pbc')], max_length=255),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='slug',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('pbc', 'Pbc')], max_length=255),
        ),
        migrations.AlterField(
            model_name='division',
            name='chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='divisions', to='votes.chamber'),
        ),
        migrations.AlterField(
            model_name='governmentparty',
            name='chamber',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('pbc', 'Pbc')], max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='chamber_id',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('pbc', 'Pbc')], max_length=255),
        ),
        migrations.AlterField(
            model_name='policyagreementlink',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decision_links', to='votes.agreement'),
        ),
        migrations.AlterField(
            model_name='policyagreementlink',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decision_links', to='votes.policy'),
        ),
        migrations.AlterField(
            model_name='policydivisionlink',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_links', to='votes.division'),
        ),
        migrations.AlterField(
            model_name='policydivisionlink',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_links', to='votes.policy'),
        ),
    ]
