# Generated by Django 4.2.15 on 2024-08-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_alter_agreement_chamber_slug_alter_chamber_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentparty',
            name='chamber',
        ),
        migrations.AddField(
            model_name='governmentparty',
            name='chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='government_parties', to='votes.chamber'),
        ),
    ]
