# Generated by Django 4.2.15 on 2024-08-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0010_agreement_chamber_division_chamber_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='chamber_id',
        ),
        migrations.AddField(
            model_name='policy',
            name='chamber',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='policies', to='votes.chamber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='chamber_slug',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('pbc', 'Pbc')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
