# Generated by Django 4.2.15 on 2024-12-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0010_userpersonlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='whipreport',
            name='evidence_detai',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='whipreport',
            name='evidence_type',
            field=models.CharField(choices=[('from_rep', 'From Rep'), ('from_whip', 'From Whip'), ('from_reporting', 'From Reporting'), ('from_other', 'From Other')], default='from_other', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whipreport',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whip_reports', to='votes.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='divisionannotation',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AgreementAnnotation',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('detail', models.CharField(default='', max_length=255)),
                ('link', models.CharField(default='', max_length=255)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreement_annotations', to='votes.agreement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
