# Generated by Django 4.2.15 on 2024-08-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_remove_policy_chamber_id_policy_chamber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='partial_hash',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
