# Generated by Django 4.2.15 on 2024-08-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0012_policy_partial_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='partial_hash',
            new_name='policy_hash',
        ),
    ]
