# Generated by Django 4.2.15 on 2024-12-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0012_rename_evidence_detai_whipreport_evidence_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='motion_type',
            field=models.CharField(choices=[('amendment', 'Amendment'), ('ten_minute_rule', 'Ten Minute Rule'), ('lords_amendment', 'Lords Amendment'), ('first_stage', 'First Stage'), ('second_stage', 'Second Stage'), ('committee_clause', 'Committee Clause'), ('second_stage_committee', 'Second Stage Committee'), ('third_stage', 'Third Stage'), ('closure', 'Closure'), ('programme', 'Programme'), ('approve_statutory_instrument', 'Approve Statutory Instrument'), ('revoke_statutory_instrument', 'Revoke Statutory Instrument'), ('adjournment', 'Adjournment'), ('timetable_change', 'Timetable Change'), ('humble_address', 'Humble Address'), ('government_agenda', 'Government Agenda'), ('financial', 'Financial'), ('confidence', 'Confidence'), ('standing_order_change', 'Standing Order Change'), ('private_sitting', 'Private Sitting'), ('eu_document_scrutiny', 'Eu Document Scrutiny'), ('other', 'Other'), ('proposed_clause', 'Proposed Clause'), ('bill_introduction', 'Bill Introduction'), ('unknown', 'Unknown'), ('reasoned_amendment', 'Reasoned Amendment')], max_length=255),
        ),
    ]
