# Generated by Django 4.2.15 on 2025-02-11 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0013_alter_motion_motion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='chamber',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreements', to='votes.chamber'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='motion',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreements', to='votes.motion'),
        ),
        migrations.AlterField(
            model_name='agreementannotation',
            name='agreement',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreement_annotations', to='votes.agreement'),
        ),
        migrations.AlterField(
            model_name='division',
            name='chamber',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='divisions', to='votes.chamber'),
        ),
        migrations.AlterField(
            model_name='division',
            name='motion',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='divisions', to='votes.motion'),
        ),
        migrations.AlterField(
            model_name='divisionannotation',
            name='division',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_annotations', to='votes.division'),
        ),
        migrations.AlterField(
            model_name='divisionbreakdown',
            name='division',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='overall_breakdowns', to='votes.division'),
        ),
        migrations.AlterField(
            model_name='divisionpartybreakdown',
            name='division',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_breakdowns', to='votes.division'),
        ),
        migrations.AlterField(
            model_name='divisionpartybreakdown',
            name='party',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_breakdowns', to='votes.organization'),
        ),
        migrations.AlterField(
            model_name='divisionsisgovbreakdown',
            name='division',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='is_gov_breakdowns', to='votes.division'),
        ),
        migrations.AlterField(
            model_name='divisiontag',
            name='division',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tags', to='votes.division'),
        ),
        migrations.AlterField(
            model_name='governmentparty',
            name='chamber',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='government_parties', to='votes.chamber'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='chamber',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_memberships', to='votes.chamber'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='effective_party',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='effective_party_memberships', to='votes.organization'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='party',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_memberships', to='votes.organization'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='votes.person'),
        ),
        migrations.AlterField(
            model_name='orgmembershipcount',
            name='chamber',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_membership_counts', to='votes.organization'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='chamber',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='policies', to='votes.chamber'),
        ),
        migrations.AlterField(
            model_name='policyagreementlink',
            name='decision',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreement_links', to='votes.agreement'),
        ),
        migrations.AlterField(
            model_name='policyagreementlink',
            name='policy',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreement_links', to='votes.policy'),
        ),
        migrations.AlterField(
            model_name='policycomparisonperiod',
            name='chamber',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comparison_periods', to='votes.chamber'),
        ),
        migrations.AlterField(
            model_name='policydivisionlink',
            name='decision',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_links', to='votes.division'),
        ),
        migrations.AlterField(
            model_name='policydivisionlink',
            name='policy',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_links', to='votes.policy'),
        ),
        migrations.AlterField(
            model_name='rebellionrate',
            name='person',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rebellion_rates', to='votes.person'),
        ),
        migrations.AlterField(
            model_name='userpersonlink',
            name='person',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_person_links', to='votes.person'),
        ),
        migrations.AlterField(
            model_name='userpersonlink',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_person_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='division',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='votes.division'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='membership',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='votes.membership'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='person',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='votes.person'),
        ),
        migrations.AlterField(
            model_name='voteannotation',
            name='division',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vote_annotations', to='votes.division'),
        ),
        migrations.AlterField(
            model_name='voteannotation',
            name='person',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vote_annotations', to='votes.person'),
        ),
        migrations.AlterField(
            model_name='votedistribution',
            name='chamber',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vote_distributions', to='votes.chamber'),
        ),
        migrations.AlterField(
            model_name='votedistribution',
            name='party',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vote_distributions', to='votes.organization'),
        ),
        migrations.AlterField(
            model_name='votedistribution',
            name='period',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vote_distributions', to='votes.policycomparisonperiod'),
        ),
        migrations.AlterField(
            model_name='votedistribution',
            name='person',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vote_distributions', to='votes.person'),
        ),
        migrations.AlterField(
            model_name='votedistribution',
            name='policy',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vote_distributions', to='votes.policy'),
        ),
        migrations.AlterField(
            model_name='whipreport',
            name='division',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whip_reports', to='votes.division'),
        ),
        migrations.AlterField(
            model_name='whipreport',
            name='party',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='whip_reports', to='votes.organization'),
        ),
    ]
