# Generated by Django 4.2.15 on 2025-03-30 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0015_divisionbreakdown_teller_against_motion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementTagLink',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('extra_data', models.JSONField(default=dict)),
                ('agreement', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_links', to='votes.agreement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionTag',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('tag_type', models.CharField(choices=[('gov_clusters', 'Gov Clusters')], max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DivisionTagLink',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('extra_data', models.JSONField(default=dict)),
                ('division', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_links', to='votes.division')),
                ('tag', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_tag_links', to='votes.decisiontag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DivisionTag',
        ),
        migrations.AddField(
            model_name='agreementtaglink',
            name='tag',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreement_tag_links', to='votes.decisiontag'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tags',
            field=models.ManyToManyField(related_name='agreements', through='votes.AgreementTagLink', to='votes.decisiontag'),
        ),
        migrations.AddField(
            model_name='division',
            name='tags',
            field=models.ManyToManyField(related_name='divisions', through='votes.DivisionTagLink', to='votes.decisiontag'),
        ),
    ]
