# Generated by Django 4.2.15 on 2024-09-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0015_organization_person_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='effective_party_slug',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
