# Generated by Django 4.2.15 on 2024-09-02 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0016_membership_effective_party_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMembershipCount',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('chamber_slug', models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('pbc', 'Pbc')], max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('count', models.IntegerField()),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_membership_counts', to='votes.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
