# Generated by Django 4.2.15 on 2025-04-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0016_agreementtaglink_decisiontag_divisiontaglink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontag',
            name='tag_type',
            field=models.CharField(choices=[('gov_clusters', 'Gov Clusters'), ('misc', 'Misc'), ('parl_bills', 'Parl Bills')], max_length=255),
        ),
    ]
