# Generated by Django 4.2.15 on 2024-09-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0017_orgmembershipcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='total_possible_members',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
