# Generated by Django 4.2.15 on 2025-05-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0019_decisiontag_extra_data_alter_decisiontag_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='update',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
