# Generated by Django 4.2.15 on 2025-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0020_update_error_message_update_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='created_via',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='update',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
