# Generated by Django 4.2.15 on 2024-09-02 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0020_governmentparty_chamber_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='absent_total',
        ),
        migrations.RemoveField(
            model_name='division',
            name='abstain_total',
        ),
        migrations.RemoveField(
            model_name='division',
            name='majority_vote',
        ),
        migrations.RemoveField(
            model_name='division',
            name='no_total',
        ),
        migrations.RemoveField(
            model_name='division',
            name='yes_total',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('aye', 'Aye'), ('no', 'No'), ('abstention', 'Abstention'), ('absent', 'Absent'), ('tellno', 'Tellno'), ('tellaye', 'Tellaye'), ('collective', 'Collective')], max_length=255)),
                ('effective_vote', models.CharField(choices=[('aye', 'Aye'), ('no', 'No'), ('abstention', 'Abstention'), ('absent', 'Absent'), ('tellno', 'Tellno'), ('tellaye', 'Tellaye'), ('collective', 'Collective')], max_length=255)),
                ('effective_party_slug', models.CharField(max_length=255)),
                ('is_gov', models.BooleanField()),
                ('effective_vote_int', models.IntegerField()),
                ('diff_from_party_average', models.FloatField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='votes.division')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='votes.membership')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='votes.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DivisionsIsGovBreakdown',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('is_gov', models.BooleanField()),
                ('vote_participant_count', models.IntegerField()),
                ('total_possible_members', models.IntegerField()),
                ('for_motion', models.IntegerField()),
                ('against_motion', models.IntegerField()),
                ('neutral_motion', models.IntegerField()),
                ('absent_motion', models.IntegerField()),
                ('signed_votes', models.IntegerField()),
                ('motion_majority', models.IntegerField()),
                ('for_motion_percentage', models.FloatField()),
                ('motion_result_int', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='is_gov_breakdowns', to='votes.division')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DivisionPartyBreakdown',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('party_slug', models.CharField(max_length=255)),
                ('vote_participant_count', models.IntegerField()),
                ('total_possible_members', models.IntegerField()),
                ('for_motion', models.IntegerField()),
                ('against_motion', models.IntegerField()),
                ('neutral_motion', models.IntegerField()),
                ('absent_motion', models.IntegerField()),
                ('signed_votes', models.IntegerField()),
                ('motion_majority', models.IntegerField()),
                ('for_motion_percentage', models.FloatField()),
                ('motion_result_int', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_breakdowns', to='votes.division')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_breakdowns', to='votes.governmentparty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DivisionBreakdown',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('vote_participant_count', models.IntegerField()),
                ('total_possible_members', models.IntegerField()),
                ('for_motion', models.IntegerField()),
                ('against_motion', models.IntegerField()),
                ('neutral_motion', models.IntegerField()),
                ('absent_motion', models.IntegerField()),
                ('signed_votes', models.IntegerField()),
                ('motion_majority', models.IntegerField()),
                ('for_motion_percentage', models.FloatField()),
                ('motion_result_int', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='breakdowns', to='votes.division')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
