# Generated by Django 4.2.15 on 2025-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0021_alter_update_created_via_alter_update_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='update',
            name='created_via',
            field=models.CharField(max_length=255),
        ),
    ]
