# Generated by Django 4.2.15 on 2025-06-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0024_bulkapiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontag',
            name='tag_type',
            field=models.CharField(choices=[('gov_clusters', 'Gov Clusters'), ('statement_tags', 'Statement Tags'), ('misc', 'Misc'), ('legislation', 'Legislation')], max_length=255),
        ),
    ]
