# Generated by Django 4.2.15 on 2025-06-23 20:17

from django.db import migrations, models
import django.db.models.deletion
import votes.consts


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0025_alter_decisiontag_tag_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('chamber_slug', models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('other', 'Other')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('statement_text', models.TextField()),
                ('original_id', models.CharField(blank=True, max_length=255, null=True)),
                ('info_source', models.CharField(default='', max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('proposed_motion', 'Proposed Motion'), ('proposed_amendment', 'Proposed Amendment'), ('letter', 'Letter'), ('other', 'Other')], default=votes.consts.StatementType['OTHER'], max_length=255)),
                ('extra_info', models.JSONField()),
                ('url', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='agreement',
            name='chamber_slug',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='slug',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='division',
            name='chamber_slug',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='governmentparty',
            name='chamber_slug',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='orgmembershipcount',
            name='chamber_slug',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='chamber_slug',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='policycomparisonperiod',
            name='chamber_slug',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('senedd', 'Senedd'), ('ni', 'Ni'), ('other', 'Other')], max_length=255),
        ),
        migrations.CreateModel(
            name='StatementTagLink',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('extra_data', models.JSONField(default=dict)),
                ('statement', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_links', to='votes.statement')),
                ('tag', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='statement_tag_links', to='votes.decisiontag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='statement',
            name='chamber',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='statements', to='votes.chamber'),
        ),
        migrations.AddField(
            model_name='statement',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='statements', through='votes.StatementTagLink', to='votes.decisiontag'),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=999)),
                ('withdrawn', models.BooleanField(default=False)),
                ('withdrawn_date', models.DateField(blank=True, default=None, null=True)),
                ('extra_info', models.JSONField()),
                ('person', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='signatures', to='votes.person')),
                ('statement', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='signatures', to='votes.statement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
