# Generated by Django 4.2.15 on 2025-07-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0026_statement_alter_agreement_chamber_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whipreport',
            name='whip_priority',
            field=models.CharField(choices=[('free', 'Free'), ('one_line', 'One Line'), ('two_line', 'Two Line'), ('three_line', 'Three Line'), ('unknown', 'Unknown')], max_length=255),
        ),
    ]
