# Generated by Django 4.2.15 on 2025-09-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0027_alter_whipreport_whip_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementPartyBreakdown',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('party', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='statement_party_breakdowns', to='votes.organization')),
                ('statement', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_breakdowns', to='votes.statement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
