# Generated by Django 4.2.15 on 2025-09-08 15:22

from django.db import migrations, models
import django.db.models.deletion
import votes.consts


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0028_statementpartybreakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='signatures', to='votes.person'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='type',
            field=models.CharField(choices=[('proposed_motion', 'Proposed Motion'), ('proposed_amendment', 'Proposed Amendment'), ('letter', 'Letter'), ('negative_si_request', 'Negative Si Request'), ('other', 'Other')], default=votes.consts.StatementType['OTHER'], max_length=255),
        ),
    ]
