# Generated by Django 5.2.17 on 2026-08-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0029_alter_signature_person_alter_statement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='agreements', through='votes.AgreementTagLink', through_fields=('agreement', 'tag'), to='votes.decisiontag'),
        ),
        migrations.AlterField(
            model_name='division',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='divisions', through='votes.DivisionTagLink', through_fields=('division', 'tag'), to='votes.decisiontag'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='statements', through='votes.StatementTagLink', through_fields=('statement', 'tag'), to='votes.decisiontag'),
        ),
    ]
