# Generated by Django 4.2.15 on 2024-08-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chamber_slug', models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('ni', 'Ni')], max_length=255)),
                ('date', models.DateTimeField()),
                ('decision_ref', models.CharField(max_length=255)),
                ('decision_name', models.IntegerField()),
                ('voting_cluster', models.CharField(default='Agreement', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('chamber_slug', models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('ni', 'Ni')], max_length=255)),
                ('date', models.DateTimeField()),
                ('division_id', models.IntegerField()),
                ('division_number', models.IntegerField()),
                ('division_name', models.CharField(max_length=255)),
                ('source_url', models.CharField(max_length=255)),
                ('motion', models.CharField(max_length=255)),
                ('manual_motion', models.CharField(max_length=255)),
                ('debate_url', models.CharField(max_length=255)),
                ('source_gid', models.CharField(max_length=255)),
                ('debate_gid', models.CharField(max_length=255)),
                ('clock_time', models.CharField(default='', max_length=255)),
                ('voting_cluster', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GovernmentParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('ni', 'Ni')], max_length=255)),
                ('party', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
