# Generated by Django 4.2.15 on 2024-09-17 12:02

from django.db import migrations, models
import django.db.models.deletion
import votes.consts


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                (
                    "chamber_slug",
                    models.CharField(
                        choices=[
                            ("commons", "Commons"),
                            ("lords", "Lords"),
                            ("scotland", "Scotland"),
                            ("senedd", "Senedd"),
                            ("ni", "Ni"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date", models.DateField()),
                ("decision_ref", models.CharField(max_length=255)),
                ("decision_name", models.CharField(max_length=255)),
                (
                    "voting_cluster",
                    models.CharField(default="Agreement", max_length=255),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Chamber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("commons", "Commons"),
                            ("lords", "Lords"),
                            ("scotland", "Scotland"),
                            ("senedd", "Senedd"),
                            ("ni", "Ni"),
                        ],
                        max_length=255,
                    ),
                ),
                ("member_plural", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                (
                    "chamber_slug",
                    models.CharField(
                        choices=[
                            ("commons", "Commons"),
                            ("lords", "Lords"),
                            ("scotland", "Scotland"),
                            ("senedd", "Senedd"),
                            ("ni", "Ni"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date", models.DateField()),
                ("division_number", models.IntegerField()),
                ("division_name", models.CharField(max_length=255)),
                ("source_gid", models.CharField(max_length=255)),
                ("debate_gid", models.CharField(max_length=255)),
                ("voting_cluster", models.CharField(default="", max_length=255)),
                ("total_possible_members", models.IntegerField()),
                (
                    "chamber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="divisions",
                        to="votes.chamber",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("party_slug", models.CharField(max_length=255)),
                ("effective_party_slug", models.CharField(max_length=255)),
                ("chamber_slug", models.CharField(max_length=255)),
                ("post_label", models.CharField(max_length=255)),
                ("area_name", models.CharField(max_length=255)),
                (
                    "chamber",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="org_memberships",
                        to="votes.chamber",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("chamber", "Chamber"),
                            ("party", "Party"),
                            ("metro", "Metro"),
                            ("unknown", "Unknown"),
                        ],
                        default=votes.consts.OrganisationType["UNKNOWN"],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("context_description", models.TextField()),
                ("policy_description", models.TextField()),
                ("notes", models.TextField(default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("candidate", "Candidate"),
                            ("draft", "Draft"),
                            ("rejected", "Rejected"),
                            ("retired", "Retired"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "strength_meaning",
                    models.CharField(
                        choices=[("classic", "Classic"), ("simplified", "Simplified")],
                        default=votes.consts.StrengthMeaning["SIMPLIFIED"],
                        max_length=255,
                    ),
                ),
                ("highlightable", models.BooleanField(default=False)),
                (
                    "chamber_slug",
                    models.CharField(
                        choices=[
                            ("commons", "Commons"),
                            ("lords", "Lords"),
                            ("scotland", "Scotland"),
                            ("senedd", "Senedd"),
                            ("ni", "Ni"),
                        ],
                        max_length=255,
                    ),
                ),
                ("policy_hash", models.CharField(max_length=255)),
                (
                    "chamber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="policies",
                        to="votes.chamber",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PolicyComparisonPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "chamber_slug",
                    models.CharField(
                        choices=[
                            ("commons", "Commons"),
                            ("lords", "Lords"),
                            ("scotland", "Scotland"),
                            ("senedd", "Senedd"),
                            ("ni", "Ni"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "chamber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="comparison_periods",
                        to="votes.chamber",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PolicyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("misc", "Misc"),
                            ("social", "Social"),
                            ("reform", "Reform"),
                            ("foreignpolicy", "Foreignpolicy"),
                            ("environment", "Environment"),
                            ("education", "Education"),
                            ("taxation", "Taxation"),
                            ("business", "Business"),
                            ("transport", "Transport"),
                            ("housing", "Housing"),
                            ("home", "Home"),
                            ("justice", "Justice"),
                            ("welfare", "Welfare"),
                        ],
                        max_length=255,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VoteDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("is_target", models.IntegerField()),
                ("num_votes_same", models.FloatField()),
                ("num_strong_votes_same", models.FloatField()),
                ("num_votes_different", models.FloatField()),
                ("num_strong_votes_different", models.FloatField()),
                ("num_votes_absent", models.FloatField()),
                ("num_strong_votes_absent", models.FloatField()),
                ("num_votes_abstain", models.FloatField()),
                ("num_strong_votes_abstain", models.FloatField()),
                ("num_agreements_same", models.FloatField()),
                ("num_strong_agreements_same", models.FloatField()),
                ("num_agreements_different", models.FloatField()),
                ("num_strong_agreements_different", models.FloatField()),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                ("distance_score", models.FloatField()),
                (
                    "chamber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vote_distributions",
                        to="votes.chamber",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vote_distributions",
                        to="votes.organization",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vote_distributions",
                        to="votes.policycomparisonperiod",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vote_distributions",
                        to="votes.person",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vote_distributions",
                        to="votes.policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("effective_vote_float", models.FloatField(null=True)),
                ("diff_from_party_average", models.FloatField(null=True)),
                (
                    "vote",
                    models.IntegerField(
                        choices=[
                            (1, "Aye"),
                            (2, "No"),
                            (3, "Abstain"),
                            (4, "Absent"),
                            (5, "Tellno"),
                            (6, "Tellaye"),
                            (7, "Collective"),
                        ]
                    ),
                ),
                (
                    "effective_vote",
                    models.IntegerField(
                        choices=[
                            (1, "Aye"),
                            (2, "No"),
                            (3, "Abstain"),
                            (4, "Absent"),
                            (5, "Tellno"),
                            (6, "Tellaye"),
                            (7, "Collective"),
                        ]
                    ),
                ),
                ("is_gov", models.BooleanField()),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="votes",
                        to="votes.division",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="votes",
                        to="votes.membership",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="votes",
                        to="votes.person",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PolicyDivisionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("agree", "Agree"),
                            ("against", "Against"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        choices=[("weak", "Weak"), ("strong", "Strong")],
                        default=votes.consts.PolicyStrength["WEAK"],
                        max_length=255,
                    ),
                ),
                ("notes", models.CharField(default="", max_length=255)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="division_links",
                        to="votes.division",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="division_links",
                        to="votes.policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PolicyAgreementLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("agree", "Agree"),
                            ("against", "Against"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        choices=[("weak", "Weak"), ("strong", "Strong")],
                        default=votes.consts.PolicyStrength["WEAK"],
                        max_length=255,
                    ),
                ),
                ("notes", models.CharField(default="", max_length=255)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="agreement_links",
                        to="votes.agreement",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="agreement_links",
                        to="votes.policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="policy",
            name="groups",
            field=models.ManyToManyField(
                related_name="policies", to="votes.policygroup"
            ),
        ),
        migrations.CreateModel(
            name="OrgMembershipCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                (
                    "chamber_slug",
                    models.CharField(
                        choices=[
                            ("commons", "Commons"),
                            ("lords", "Lords"),
                            ("scotland", "Scotland"),
                            ("senedd", "Senedd"),
                            ("ni", "Ni"),
                        ],
                        max_length=255,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("count", models.IntegerField()),
                (
                    "chamber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="org_membership_counts",
                        to="votes.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="effective_party",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="effective_party_memberships",
                to="votes.organization",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="party",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="party_memberships",
                to="votes.organization",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="memberships",
                to="votes.person",
            ),
        ),
        migrations.CreateModel(
            name="GovernmentParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "chamber_slug",
                    models.CharField(
                        choices=[
                            ("commons", "Commons"),
                            ("lords", "Lords"),
                            ("scotland", "Scotland"),
                            ("senedd", "Senedd"),
                            ("ni", "Ni"),
                        ],
                        max_length=255,
                    ),
                ),
                ("party", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "chamber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="government_parties",
                        to="votes.chamber",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DivisionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tag_type",
                    models.CharField(
                        choices=[("gov_clusters", "Gov Clusters")], max_length=255
                    ),
                ),
                ("analysis_data", models.CharField(max_length=255)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="analyses",
                        to="votes.division",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DivisionsIsGovBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("is_gov", models.BooleanField()),
                ("vote_participant_count", models.IntegerField()),
                ("total_possible_members", models.IntegerField()),
                ("for_motion", models.IntegerField()),
                ("against_motion", models.IntegerField()),
                ("neutral_motion", models.IntegerField()),
                ("absent_motion", models.IntegerField()),
                ("signed_votes", models.IntegerField()),
                ("motion_majority", models.IntegerField()),
                ("for_motion_percentage", models.FloatField()),
                ("motion_result_int", models.IntegerField()),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="is_gov_breakdowns",
                        to="votes.division",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DivisionPartyBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("party_slug", models.CharField(max_length=255)),
                ("vote_participant_count", models.IntegerField()),
                ("total_possible_members", models.IntegerField()),
                ("for_motion", models.IntegerField()),
                ("against_motion", models.IntegerField()),
                ("neutral_motion", models.IntegerField()),
                ("absent_motion", models.IntegerField()),
                ("signed_votes", models.IntegerField()),
                ("motion_majority", models.IntegerField()),
                ("for_motion_percentage", models.FloatField()),
                ("motion_result_int", models.IntegerField()),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="party_breakdowns",
                        to="votes.division",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="party_breakdowns",
                        to="votes.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DivisionBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("vote_participant_count", models.IntegerField()),
                ("total_possible_members", models.IntegerField()),
                ("for_motion", models.IntegerField()),
                ("against_motion", models.IntegerField()),
                ("neutral_motion", models.IntegerField()),
                ("absent_motion", models.IntegerField()),
                ("signed_votes", models.IntegerField()),
                ("motion_majority", models.IntegerField()),
                ("for_motion_percentage", models.FloatField()),
                ("motion_result_int", models.IntegerField()),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="breakdowns",
                        to="votes.division",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="agreement",
            name="chamber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="agreements",
                to="votes.chamber",
            ),
        ),
    ]
