# Generated by Django 4.2.15 on 2024-10-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='voting_cluster',
        ),
        migrations.RemoveField(
            model_name='division',
            name='voting_cluster',
        ),
        migrations.AlterField(
            model_name='divisionbreakdown',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='overall_breakdowns', to='votes.division'),
        ),
        migrations.AlterField(
            model_name='divisiontag',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tags', to='votes.division'),
        ),
    ]
