# Generated by Django 4.2.15 on 2024-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_alter_agreement_date_alter_division_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentparty',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
