# Generated by Django 4.2.15 on 2024-11-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_motion_agreement_motion_division_motion'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='division_info_source',
            field=models.CharField(default='', max_length=255),
        ),
    ]
