# Generated by Django 4.2.15 on 2024-11-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_division_division_info_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebellionRate',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('period_type', models.IntegerField(choices=[(0, 'Alltime'), (1, 'Year'), (2, 'Period')])),
                ('period_number', models.IntegerField()),
                ('value', models.FloatField()),
                ('total_votes', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rebellion_rates', to='votes.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
