# Generated by Django 4.2.15 on 2024-08-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_policy_policygroup_remove_division_clock_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='debate_url',
        ),
    ]
