# Generated by Django 4.2.15 on 2024-12-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_rebellionrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='negative',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
