# Generated by Django 4.2.15 on 2024-08-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_remove_division_debate_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('slug', models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('ni', 'Ni'), ('pbc', 'Pbc')], max_length=255)),
                ('member_plural', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='division',
            name='chamber_slug',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='chamber_slug',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('ni', 'Ni'), ('pbc', 'Pbc')], max_length=255),
        ),
        migrations.AlterField(
            model_name='governmentparty',
            name='chamber',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('ni', 'Ni'), ('pbc', 'Pbc')], max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='chamber_id',
            field=models.CharField(choices=[('commons', 'Commons'), ('lords', 'Lords'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('ni', 'Ni'), ('pbc', 'Pbc')], max_length=255),
        ),
        migrations.AddField(
            model_name='division',
            name='chamber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='votes.chamber'),
            preserve_default=False,
        ),
    ]
