# Generated by Django 4.2.15 on 2024-12-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0007_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhipReport',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('whip_direction', models.CharField(choices=[('for', 'For'), ('against', 'Against'), ('abstain', 'Abstain'), ('free', 'Free')], max_length=255)),
                ('whip_priority', models.CharField(choices=[('free', 'Free'), ('one_line', 'One Line'), ('two_line', 'Two Line'), ('three_line', 'Three Line')], max_length=255)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='whip_reports', to='votes.division')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteAnnotation',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('detail', models.CharField(default='', max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vote_annotations', to='votes.division')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vote_annotations', to='votes.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DivisionAnnotation',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('detail', models.CharField(default='', max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='division_annotations', to='votes.division')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
