# Generated by Django 4.2.15 on 2024-12-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_whipreport_voteannotation_divisionannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisOverride',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('decision_key', models.CharField(max_length=255)),
                ('banned_motion_ids', models.TextField(blank=True, default='')),
                ('parl_dynamics_group', models.CharField(blank=True, default='', max_length=255)),
                ('manual_parl_dynamics_desc', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
