# Generated by Django 4.2.15 on 2024-12-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_whipreport_evidence_detai_whipreport_evidence_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whipreport',
            old_name='evidence_detai',
            new_name='evidence_detail',
        ),
    ]
