# Generated by Django 4.2.15 on 2024-09-01 18:50

from django.db import migrations, models
import django.db.models.deletion
import votes.consts


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0014_alter_agreement_id_alter_chamber_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('chamber', 'Chamber'), ('party', 'Party'), ('metro', 'Metro'), ('unknown', 'Unknown')], default=votes.consts.OrganisationType['UNKNOWN'], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('party_slug', models.CharField(max_length=255)),
                ('post_label', models.CharField(max_length=255)),
                ('area_name', models.CharField(max_length=255)),
                ('on_behalf_of', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_memberships', to='votes.organization')),
                ('organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_memberships', to='votes.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='votes.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
