# Generated by Django 4.2.15 on 2024-09-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0022_remove_vote_effective_vote_int_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyagreementlink',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreement_links', to='votes.agreement'),
        ),
        migrations.AlterField(
            model_name='policyagreementlink',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreement_links', to='votes.policy'),
        ),
    ]
