# Generated by Django 4.2.15 on 2024-09-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0024_membership_chamber_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='chamber_slug',
            field=models.CharField(max_length=255),
        ),
    ]
