# Generated by Django 4.2.15 on 2024-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0025_alter_membership_chamber_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='effective_vote_float',
            field=models.FloatField(null=True),
        ),
    ]
