# Generated by Django 4.2.15 on 2024-09-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0027_alter_vote_diff_from_party_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionTag',
            fields=[
                ('id', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('tag_type', models.CharField(choices=[('gov_clusters', 'Gov Clusters')], max_length=255)),
                ('analysis_data', models.CharField(max_length=255)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analyses', to='votes.division')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
