# Generated by Django 4.2.15 on 2024-09-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0028_divisiontag"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyComparisonPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "chamber_slug",
                    models.CharField(
                        choices=[
                            ("commons", "Commons"),
                            ("lords", "Lords"),
                            ("scotland", "Scotland"),
                            ("senedd", "Senedd"),
                            ("ni", "Ni"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "chamber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="comparison_periods",
                        to="votes.chamber",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
