# Generated by Django 4.2.15 on 2024-09-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0029_policycomparisonperiod"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelevantPolicyLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="relevant_links",
                        to="votes.policycomparisonperiod",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="relevant_links",
                        to="votes.person",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="relevant_links",
                        to="votes.policy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
