# Generated by Django 4.2.15 on 2024-09-15 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0030_relevantpolicylink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="chamber",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="org_memberships",
                to="votes.chamber",
            ),
        ),
    ]
