# Generated by Django 4.2.15 on 2024-09-15 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0031_alter_membership_chamber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divisionpartybreakdown",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="party_breakdowns",
                to="votes.organization",
            ),
        ),
    ]
