# Generated by Django 4.2.15 on 2024-09-16 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0032_alter_divisionpartybreakdown_party"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="effective_party",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="effective_party_memberships",
                to="votes.organization",
            ),
        ),
    ]
