# Generated by Django 4.2.15 on 2024-09-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0034_votedistribution"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RelevantPolicyLink",
        ),
    ]
