# Generated by Django 4.2.15 on 2024-09-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0035_delete_relevantpolicylink"),
    ]

    operations = [
        migrations.RenameField(
            model_name="votedistribution",
            old_name="comparison",
            new_name="period",
        ),
    ]
