# Generated by Django 4.2.15 on 2024-09-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0036_rename_comparison_votedistribution_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="effective_party_slug",
        ),
        migrations.AlterField(
            model_name="vote",
            name="effective_vote",
            field=models.IntegerField(
                choices=[
                    (1, "Aye"),
                    (2, "No"),
                    (3, "Abstain"),
                    (4, "Absent"),
                    (5, "Tellno"),
                    (6, "Tellaye"),
                    (7, "Collective"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="vote",
            field=models.IntegerField(
                choices=[
                    (1, "Aye"),
                    (2, "No"),
                    (3, "Abstain"),
                    (4, "Absent"),
                    (5, "Tellno"),
                    (6, "Tellaye"),
                    (7, "Collective"),
                ]
            ),
        ),
    ]
