# Run linting and basic file format checks

name: Lint

on:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.11'
      - name: run ruff linter and formatter
        run: |-
          pip install ruff==0.6.2 djlint==1.35.4
          ruff check .
          ruff format . --check
          djlint votes/templates --reformat --quiet