# Run linting and basic file format checks

name: Test

on:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests and try and build project
        uses: mysociety/run-in-devcontainer@v1
        with:
          dockerfile: Dockerfile
          app: web
          run: |
            script/setup
            script/populate --all
            script/populate --all --update-last 5
            script/test
     
    